services:
  web:
    build: .
    container_name: spineup
    command: >
      sh -c "
      python3 manage.py makemigrations --noinput &&
      python3 manage.py migrate --noinput &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./src/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_spineup:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TIME_ZONE: ${TIME_ZONE}
      USE_TZ: ${USE_TZ}


volumes:
    postgres_data_spineup: